// 'use client'
// import { useTheme } from '@emotion/react'
import { Box, useTheme } from '@mui/material'
import Head from 'next/head'
import { ReactNode } from 'react'
import CustomDataGrid from 'src/components/custom-data-grid'
import CustomTextField from 'src/components/text-field'
import { useSettings } from 'src/hooks/useSettings'
import LayoutNotApp from 'src/views/layouts/LayoutNotApp'
// ** Pages
import HomePage from 'src/views/pages/home'

export default function Home() {
  const theme = useTheme()
  const { settings } = useSettings()

  // console.log('theme', {theme, settings})

  return (
    <>
      <Head>
        <title>Lập trình thật dễ</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <HomePage />
    </>
  )
}

Home.getLayout = (page: ReactNode) => <LayoutNotApp>{page}</LayoutNotApp>

//trang Home cả khách và user đều vào được => truyên 2 biến là false hết để trang return về {children} luôn
Home.guestGuard = false
Home.authGuard = false
