// 'use client'
// import { useTheme } from '@emotion/react'
import { Box,useTheme } from '@mui/material'
import Head from 'next/head'
import { ReactNode } from 'react'
import CustomTextField from 'src/components/text-field'
import { useSettings } from 'src/hooks/useSettings'
import LayoutNotApp from 'src/views/layouts/LayoutNotApp'

export default function Home() {
  const theme =useTheme()
  const {settings} = useSettings()
  
  // console.log('theme', {theme, settings})

  return (
    <>
      <Head>
        <title>Lập trình thật dễ</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Box sx={{margin:6, width:"200px"}}><CustomTextField  id="outlined-multiline-flexible" label="Multiline" /></Box>
    </>
  )
}

Home.getLayout = (page: ReactNode) => <LayoutNotApp>{page}</LayoutNotApp>

